### ISSUE TITLE
Top of page gradients missing from edited themes.

### ISSUE THREAD

**Issue by tallos** [nebukazar/OneeChan#44] opened 2015-01-10 22:13 UTC
After updating to 5.5.12 and fixing the color of backlinks and quotelinks to as they where in 5.5.11(Backlink: 66182d, Quotelink: 34345c) the gradient that goes from the top of the page to the first post is missing from the edited theme.

Please add a way to re-enable the gradient in edited themes.

**Comment by nebukazar** [comment] 2015-01-11 14:19
I assume you're talking about Yotsuba (B). Thanks for bringing this to my attention, it should be fixed in 5.5.13. Both themes should look pretty much like their originals now.

**Comment by tallos** [comment] 2015-01-12 14:04
Backlinks and Quotelinks are still a different color in Yotsuba (B) compared to 5.5.11.

5.5.13+ is quotelink: dd0000 , backlink: 34345c
5.5.11 was quotelink: 34345c ,  backlink: 66182d

**Comment by nebukazar** [comment] 2015-01-12 19:12
Yes, I understand but those quotelink colors are not like the original Yotsuba B. Before it looked like:

![theme](https://cloud.githubusercontent.com/assets/5222254/5708964/cc9be668-9a95-11e4-9a5c-ca9285f1d6b9.png)

Now it looks like:

![theme](https://cloud.githubusercontent.com/assets/5222254/5708917/79ca6c2a-9a95-11e4-83ef-f648a9ef88f4.png)

I figure when people pick the Yotsuba B theme they're looking for the same theme as the original 4chan theme except with the added 4chan X/OneeChan functionality. Going back to those colors would be a regression in my opinion. 

As for the reason the quotelinks were blue instead of red in previous versions (Appchan X also has red backlinks for Yotsuba B), you'd probably have to ask @seaweedchan since he was the original creator of the script and I haven't changed them since I took maintenance of the script until now. He probably thought it would look better that way and changed them.

**Comment by tallos** [comment] 2015-01-12 22:01
Ahh, i haven't used 4chan without Oneechan in so long i guess I forgot.

Thanks for your work maintaining it.

**Closed** 2015-02-23 04:25 UTC
